### PR TITLE
Typescript Declarations

### PR DESCRIPTION
**Pull request by shadowtime2000**
### Please describe your contribution:
Written Typescript declarations

### Please document your feature, changes or API below:
Created Typescript declarations for the code, and I added the `types` field to `package.json` so people can easily access it.

- [x] I have read, and my contribution follows the [Contributing Guidelines](https://github.com/eon-web/eon/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by shadowtime2000** [comment]
TODO:
- [x] Implement Classes in Structure
- [x] Add Functions
- [ ] Add Fields for classes (WIP)
- [ ] Added typings for plugin system (Plugin interface etc.)
- [ ] Look into structure and change `any` fields for better type safety

**Comment by shadowtime2000** [comment]
@codemaster138 I can't seem to find any docs for stuff like options and all which makes it hard to set their types. Are you going to add them to the docs?

**Comment by shadowtime2000** [comment]
@codemaster138 Ready for review!

**Review by codemaster138 — APPROVED** [review]
Hey @shadowtime2000! Thanks for your contribution to eon.js!

Your PR has been reviewed and will now be merged into eonjs@1.17.15

**Pull request merged**
